---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-db
  namespace: ${NAMESPACE}-app
data:
  POSTGRES_HOST: ${POSTGRES_HOST_PLAIN}
  POSTGRES_PORT: "${POSTGRES_PORT_PLAIN}"
  POSTGRES_DB: ${POSTGRES_DB_PLAIN}
  POSTGRES_USER: ${POSTGRES_USER_PLAIN}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PLAIN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-app
  namespace: ${NAMESPACE}-app
data:
  GREETINGS_MESSAGE: ${GREETINGS_MESSAGE_PLAIN}
