apiVersion: v1
kind: PersistentVolume
metadata:
  name: devsecops-db-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: devsecops-static-nfs
  nfs:
    path: /
    server: nfs-server
