apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devsecops-db-nfs
  namespace: ${NAMESPACE}-db
spec:
  accessModes:
  - ReadWriteOnce
  # Exemplo de uso de storageClass dinamico na Digital Ocean que ira criar um persistentVolume automaticamente apontando para o servi√ßo do block storage da Digital Ocean
  # storageClassName: do-block-storage
  storageClassName: devsecops-static-nfs 
  resources:
    requests:
      storage: 1Gi
