---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: ${NAMESPACE}-db
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: devsecops-db
        # Env Var Postgres Data
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data
        startupProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - "pg_isready -h localhost -p 5432 -U ${POSTGRES_USER_PLAIN} -d ${POSTGRES_DB_PLAIN}"
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 5m
            memory: 70Mi
          limits:
            cpu: 500m
            memory: 500Mi
        # Volume Mounts in Container
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      # External Volume - HostPath (Path in cluster's node)
      volumes:
      - name: postgresql-data
        hostPath:
          path: /home
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  namespace: ${NAMESPACE}-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
      - name: devsecops
        image: ghcr.io/gbrandalise/learn-devsecops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # env:
        # Secret Values
        # - name: GREETINGS_MESSAGE
        #   valueFrom:
        #     secretKeyRef:
        #       name: devsecops-app
        #       key: GREETINGS_MESSAGE
        # - name: POSTGRES_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_HOST
        # - name: POSTGRES_PORT
        #   valueFrom:
        #     secretKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_PORT
        # - name: POSTGRES_DB
        #   valueFrom:
        #     secretKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_DB
        # - name: POSTGRES_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_USER
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_PASSWORD

        # Env Vars
        # - name: GREETINGS_MESSAGE
        #   value: ${GREETINGS_MESSAGE_PLAIN}
        # - name: POSTGRES_HOST
        #   value: ${POSTGRES_HOST_PLAIN}
        # - name: POSTGRES_PORT
        #   value: "${POSTGRES_PORT_PLAIN}"
        # - name: POSTGRES_DB
        #   value: ${POSTGRES_DB_PLAIN}
        # - name: POSTGRES_USER
        #   value: ${POSTGRES_USER_PLAIN}
        # - name: POSTGRES_PASSWORD
        #   value: ${POSTGRES_PASSWORD_PLAIN}
        # - name: GREETINGS_MESSAGE

        # ConfigMap Values
        #   valueFrom:
        #     configMapKeyRef:
        #       name: devsecops-app
        #       key: GREETINGS_MESSAGE
        # - name: POSTGRES_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_HOST
        # - name: POSTGRES_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_PORT
        # - name: POSTGRES_DB
        #   valueFrom:
        #     configMapKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_DB
        # - name: POSTGRES_USER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_USER
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     configMapKeyRef:
        #       name: devsecops-db
        #       key: POSTGRES_PASSWORD
        envFrom:
        # ConfigMap Reference
        # - configMapRef:
        #     name: devsecops-db
        # - configMapRef:
        #     name: devsecops-app
        # Secret Reference
        - secretRef:
            name: devsecops-app
        - secretRef:
            name: devsecops-db
        startupProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 2
          timeoutSeconds: 3
        # QoS = Quality of Service
        # Define a priorização da eliminação dos pods caso ocorra falta de recursos nos nodes, seguindo a seguinte sequência:
        # BestEffort = Pods sem configuração de resources
        # Burstable = Pods com recursos limitados seja de requests ou limits
        # Guaranteed = Pods com recursos limitados e idênticos, tanto em requests como em limits, pois indica um pod que não altera seus limites mínimos e máximos de uso de recursos
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
