---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: devsecops-resources-development-app
  namespace: development-app
spec:
  hard:
    requests.cpu: 50m
    requests.memory: 1Gi
    limits.cpu: 2000m
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: devsecops-resources-development-db
  namespace: development-db
spec:
  hard:
    requests.cpu: 10m
    requests.memory: 100Mi
    limits.cpu: 1000m
    limits.memory: 1Gi