---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: devsecops-resources-development-app
  namespace: development-app
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 2Gi
    limits.cpu: 4000m
    limits.memory: 4Gi
    pods: "10"
    services: "5"
    services.loadbalancers: "1"
    count/deployments.app: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: devsecops-resources-development-db
  namespace: development-db
spec:
  hard:
    requests.cpu: 10m
    requests.memory: 100Mi
    limits.cpu: 1000m
    limits.memory: 1Gi